name: Check code
on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
          cache: true
      - name: Check formatting
        shell: bash
        run: |
          go vet .
          go fmt ./...
          [[ -z $(git status -s) ]] || (echo "Code is not formatted, please run go fmt ./..." && exit 1)

